# Generated by Django 2.2.2 on 2019-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190624_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
